### ISSUE TITLE
MC.EXEで発生していないエラー

### ISSUE THREAD

**Issue by pedipanol** [kuma4649/PMDDotNET#17]
ポルタメント指定のコマンドについて
PMDDotNETでこのコマンドを使えば
![image](https://user-images.githubusercontent.com/26771164/195674723-40053d5b-2d38-449d-a38f-9797a7db8a42.png)
エラー８が発生します
![image](https://user-images.githubusercontent.com/26771164/195676553-74afd4a5-994a-49bf-91c6-4c79737a43c9.png)

ですけれど、PMDのMC.EXEで同じMMLファイルをコンパイルしてみたら成功になります
![image](https://user-images.githubusercontent.com/26771164/195675430-16ca2bed-b45f-4e52-b028-42b8db591e0f.png)
.Mファイルも書いた通りプレイします

**Comment by kuma4649** [comment]
ご報告、ありがとうございます。
本件、現象を確認しましたので修正します

**Comment by kuma4649** [comment]
修正完了しました。
ご確認ください。

**Comment by pedipanol** [comment]
成功です、ありがとうございます！
