### ISSUE TITLE
#Filename が機能していない

### ISSUE THREAD

**Issue by aosoft** [kuma4649/PMDDotNET#2]
#Filename はコンパイル後に出力するバイナリのファイル名を指定するものです。

```
#Filename FUGAFUGA.M
```

拡張子だけ指定することもできます。 PMD のバイナリ拡張子は標準は .M ですが、慣例として対応音源に合わせて .M2 / .MZ などにすることになっていて、これを #Filename で指定します。

```
#Filename .M2
```

とした場合、 FUGA.MML をコンパイルして出てくるのは FUGA.M ではなく FUGA.M2 。

**Comment by aosoft** [comment]
これは多分面倒なことになるとは思います。

* 前処理として # 系のメタデーターだけを取得するメソッド (Preprocess) を追加し、事前に各種情報を取得して出力ファイル名を決定する？
* 書き出し先ストリームを生成するコールバックを定義する？

**Comment by kuma4649** [comment]
こりは。。。どうしたもんかｗ

**Comment by aosoft** [comment]
(最終的にはないと困りはしますが)致命的な事ではないので後回しでいいとは思います。
個人的には前処理で情報取得を押します。MUCOMでも同じことちょっと思ってまして、コンパイル、再生前に必要なPCMファイル名がわかると先にファイルを読み込んでおくことができるので、前処理でこれらの情報が取得できるとありがたいかなあと。

**Comment by kuma4649** [comment]
前処理としてタグの情報を取得するのって、ちょっとたいへんだなぁ。。。特にインクルードとの絡みが。独自に組んでしまったほうがいいのかなぁ。

**Comment by kuma4649** [comment]
タグを読み込む処理の追加とその情報を利用して出力ファイル名を決定するようにしました。
ご確認ください。

**Comment by aosoft** [comment]
TAG009 で確認しました。ありがとうございました。
