### ISSUE TITLE
#Option is ignored when compiling

### ISSUE THREAD

**Issue by pedipanol** [kuma4649/PMDDotNET#9]
I hope english is ok...

I often add /v to #Option on the MML so I don't have to type it every time, PMDDotNET doesn't read this option...

Example file: FM instruments aren't loaded when it's compiled without adding /v to command line
[gfree.txt](https://github.com/kuma4649/PMDDotNET/files/4581098/gfree.txt)

**Comment by kuma4649** [comment]
ありがとうございます！
早速調査します

**Comment by kuma4649** [comment]
TAG026で対応しましたので、ご確認ください。
報告よろしくお願いします！

でも、TAG027が最新です。。。
/Cオプションが常に有効になってました。
